// <auto-generated />
using System;
using EvensonFamilyTreeAppsDev.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EvensonFamilyTreeAppsDev.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EvensonFamilyTreeAppsDev.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<int?>("UserTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("UserTypeId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EvensonFamilyTreeAppsDev.Models.AuthorizedViewer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FamilyTreeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FamilyTreeId");

                    b.HasIndex("UserId");

                    b.ToTable("AuthorizedViewer");
                });

            modelBuilder.Entity("EvensonFamilyTreeAppsDev.Models.FamilyTree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FamilyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("FamilyTrees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FamilyName = "Johnson Family Tree"
                        },
                        new
                        {
                            Id = 2,
                            FamilyName = "Martinez Family Tree"
                        },
                        new
                        {
                            Id = 3,
                            FamilyName = "Evenson Family Tree"
                        });
                });

            modelBuilder.Entity("EvensonFamilyTreeAppsDev.Models.MilitaryService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MilitaryTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MilitaryTypeId");

                    b.ToTable("MilitaryServices");
                });

            modelBuilder.Entity("EvensonFamilyTreeAppsDev.Models.MilitaryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MilitaryBranch")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MilitaryType");
                });

            modelBuilder.Entity("EvensonFamilyTreeAppsDev.Models.Occupation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Occupations");
                });

            modelBuilder.Entity("EvensonFamilyTreeAppsDev.Models.Partnership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Person1Id")
                        .HasColumnType("int");

                    b.Property<int>("Person2Id")
                        .HasColumnType("int");

                    b.Property<int?>("RelationshipTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Person1Id");

                    b.HasIndex("Person2Id");

                    b.HasIndex("RelationshipTypeId");

                    b.ToTable("Partnerships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Person1Id = 1,
                            Person2Id = 2,
                            RelationshipTypeId = 1,
                            StartDate = new DateTime(1998, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Person1Id = 4,
                            Person2Id = 5,
                            RelationshipTypeId = 1,
                            StartDate = new DateTime(1990, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Person1Id = 8,
                            Person2Id = 9,
                            RelationshipTypeId = 1,
                            StartDate = new DateTime(1989, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("EvensonFamilyTreeAppsDev.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeathDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FamilyTreeId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LifeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Parent1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Parent2Id")
                        .HasColumnType("int");

                    b.Property<string>("Prefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestingPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suffix")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FamilyTreeId");

                    b.HasIndex("Parent1Id");

                    b.HasIndex("Parent2Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1970, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Chicago, IL",
                            FamilyTreeId = 1,
                            FirstName = "Robert",
                            Gender = 1,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1974, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Boston, MA",
                            FamilyTreeId = 1,
                            FirstName = "Emily",
                            Gender = 2,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2001, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Chicago, IL",
                            FamilyTreeId = 1,
                            FirstName = "Michael",
                            Gender = 1,
                            LastName = "Johnson",
                            Parent1Id = 1,
                            Parent2Id = 2
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1965, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "San Juan, PR",
                            FamilyTreeId = 2,
                            FirstName = "Carlos",
                            Gender = 1,
                            LastName = "Martinez"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1968, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Houston, TX",
                            FamilyTreeId = 2,
                            FirstName = "Ana",
                            Gender = 2,
                            LastName = "Martinez"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1998, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Houston, TX",
                            FamilyTreeId = 2,
                            FirstName = "Sophia",
                            Gender = 2,
                            LastName = "Martinez",
                            Parent1Id = 4,
                            Parent2Id = 5
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1994, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Ashland, WI",
                            FamilyTreeId = 3,
                            FirstName = "Kara",
                            Gender = 2,
                            LastName = "Evenson"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1958, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Ashland, WI",
                            FamilyTreeId = 3,
                            FirstName = "Brian",
                            Gender = 1,
                            LastName = "Evenson"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1958, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Florham Park, NJ",
                            FamilyTreeId = 3,
                            FirstName = "Kathleen",
                            Gender = 2,
                            LastName = "Evenson"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1932, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Ashland, WI",
                            FamilyTreeId = 3,
                            FirstName = "Marlene",
                            Gender = 2,
                            LastName = "Martin"
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(1943, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Grand Forks, ND",
                            DeathDate = new DateTime(2021, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FamilyTreeId = 3,
                            FirstName = "Gary",
                            Gender = 1,
                            LastName = "Martin"
                        });
                });

            modelBuilder.Entity("EvensonFamilyTreeAppsDev.Models.RelationshipType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RelationshipType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Married"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Engaged"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Divorced"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Partnered"
                        });
                });

            modelBuilder.Entity("EvensonFamilyTreeAppsDev.Models.UserStory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Story")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("UserStories");
                });

            modelBuilder.Entity("EvensonFamilyTreeAppsDev.Models.UserType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserType");
                });

            modelBuilder.Entity("EvensonFamilyTreeAppsDev.Models.AppUser", b =>
                {
                    b.HasOne("EvensonFamilyTreeAppsDev.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.HasOne("EvensonFamilyTreeAppsDev.Models.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeId");

                    b.Navigation("Person");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("EvensonFamilyTreeAppsDev.Models.AuthorizedViewer", b =>
                {
                    b.HasOne("EvensonFamilyTreeAppsDev.Models.FamilyTree", "FamilyTree")
                        .WithMany("AuthorizedViewers")
                        .HasForeignKey("FamilyTreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvensonFamilyTreeAppsDev.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FamilyTree");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EvensonFamilyTreeAppsDev.Models.FamilyTree", b =>
                {
                    b.HasOne("EvensonFamilyTreeAppsDev.Models.AppUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("EvensonFamilyTreeAppsDev.Models.MilitaryService", b =>
                {
                    b.HasOne("EvensonFamilyTreeAppsDev.Models.MilitaryType", "MilitaryType")
                        .WithMany()
                        .HasForeignKey("MilitaryTypeId");

                    b.Navigation("MilitaryType");
                });

            modelBuilder.Entity("EvensonFamilyTreeAppsDev.Models.Partnership", b =>
                {
                    b.HasOne("EvensonFamilyTreeAppsDev.Models.Person", "Person1")
                        .WithMany()
                        .HasForeignKey("Person1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvensonFamilyTreeAppsDev.Models.Person", "Person2")
                        .WithMany()
                        .HasForeignKey("Person2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvensonFamilyTreeAppsDev.Models.RelationshipType", "RelationshipType")
                        .WithMany()
                        .HasForeignKey("RelationshipTypeId");

                    b.Navigation("Person1");

                    b.Navigation("Person2");

                    b.Navigation("RelationshipType");
                });

            modelBuilder.Entity("EvensonFamilyTreeAppsDev.Models.Person", b =>
                {
                    b.HasOne("EvensonFamilyTreeAppsDev.Models.FamilyTree", "FamilyTree")
                        .WithMany("Members")
                        .HasForeignKey("FamilyTreeId");

                    b.HasOne("EvensonFamilyTreeAppsDev.Models.Person", "Parent1")
                        .WithMany("ChildrenFromParent1")
                        .HasForeignKey("Parent1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EvensonFamilyTreeAppsDev.Models.Person", "Parent2")
                        .WithMany("ChildrenFromParent2")
                        .HasForeignKey("Parent2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FamilyTree");

                    b.Navigation("Parent1");

                    b.Navigation("Parent2");
                });

            modelBuilder.Entity("EvensonFamilyTreeAppsDev.Models.UserStory", b =>
                {
                    b.HasOne("EvensonFamilyTreeAppsDev.Models.Person", "Person")
                        .WithMany("Stories")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("EvensonFamilyTreeAppsDev.Models.FamilyTree", b =>
                {
                    b.Navigation("AuthorizedViewers");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("EvensonFamilyTreeAppsDev.Models.Person", b =>
                {
                    b.Navigation("ChildrenFromParent1");

                    b.Navigation("ChildrenFromParent2");

                    b.Navigation("Stories");
                });
#pragma warning restore 612, 618
        }
    }
}
